name: opentool_dart
description: An OpenTool JSON Spec Parser for dart with ToolDrivers.
version: 0.6.1
repository: https://github.com/LiteVar/opentool_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  http: ^1.4.0
  path: ^1.9.1

  # Modbus Protocol support
  modbus_client: ^1.4.2
  modbus_client_tcp: ^1.2.3
  modbus_client_udp: ^1.4.0
  modbus_client_serial: ^1.3.1

  # json-rpc 2.0 support
  json_rpc_2: ^4.0.0

  # OpenSpec support
  openapi_dart: ^0.2.0
  openrpc_dart: ^0.2.0
  openmodbus_dart: ^0.2.0

  # OpenDyn support
  opendyn_dart: ^0.1.0

  # Serial Port support
  libserialport: ^0.3.0+1

  # MCP support
  mcp_dart: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  lints: ^5.1.1
  test: ^1.25.14

assets:
  - libs/macos/dyn_bridge
