name: opentool_dart
description: OpenTool client and server SDK for Dart, providing a JSON Spec Parser.
version: 1.1.0
repository: https://github.com/opentool-hub/opentool-dart

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  dio: ^5.8.0+1
  uuid: ^4.5.1
  snowflaker: ^1.1.0

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0